#!/usr/bin/env python
import numpy as np
from numpy import sin, cos, tan, exp, sqrt, sign, arctan as atan, abs as Abs
from __builtin__ import min as Min, max as Max

# This file is auto-generated by ekf/codegen.py. DO NOT EDIT.


def Heaviside(x):
    return 1 * (x > 0)


def DiracDelta(x, v=1):
    return x == 0 and v or 0


def initial_state():
    x = np.float32(
        [0.0, 0.0, 0.0, 0.0, 0.0, 1.70000004768372, 0.300000011920929, -2.70000004768372, -2.29999995231628, -1.60000002384186, 0.200000002980232, 4.00000000000000, -35.0000000000000, 125.000000000000, 0.0]
    )
    P = np.diag(
        [1.00000011116208e-6, 0.0100000007078052, 4.00000000000000, 1.00000000000000, 0.160000011324883, 16.0000000000000, 16.0000000000000, 16.0000000000000, 16.0000000000000, 0.250000000000000, 0.250000000000000, 0.250000000000000, 10000.0000000000, 10000.0000000000, 1.00000000000000]
    )

    return x, P


